### ISSUE TITLE
Add 256 px option for creating job

### ISSUE THREAD

**Issue by hrzepa** [ImperialCollegeLondon/hpc_portal#29]
Could a 256 processor option be added to the pull down menu at https://openondemand.rcs.ic.ac.uk/pun/sys/chemistry_portal/job_type/

It would only work with custom configurations, e.g. #PBS -q express

**Comment by hrzepa** [comment]
See comment on Github.

**Comment by hrzepa** [comment]
Suggestion for  #16.  This is what happens when a custom profile is created

#!/bin/bash
#PBS -N portal_job_00000086
#PBS -q express
#PBS -P exp-00049
#PBS -l select=1:ncpus=48:mem=120gb,walltime=72:00:00
#PBS -l select=1:ncpus=1:mem=4gb,walltime=00:30:00
export NCORES=1
export MEMORY_GB=4


The custom profile added the line 

#PBS -l select=1:ncpus=48:mem=120gb,walltime=72:00:00

But the system then appends replacement lines

#PBS -l select=1:ncpus=1:mem=4gb,walltime=00:30:00
export NCORES=1
export MEMORY_GB=4

which override the profile line  and totally negates the intended custom profile.

This must have a solution, since the whole purpose of custom profiles would then be rendered pointless.

**Comment by hrzepa** [comment]
If I try a custom profile as per attached, it is declared invalid
![profile1](https://user-images.githubusercontent.com/7828928/128623833-71ebcdab-29dd-4606-ac37-f9302655d571.jpg)

**Comment by cc-a** [comment]
Closing as this is being addressed by #16
