### ISSUE TITLE
UI for closing  View file => New tab?

### ISSUE THREAD

**Issue by hrzepa** [ImperialCollegeLondon/hpc_portal#38]
At  eg https://openondemand.rcs.ic.ac.uk/pun/sys/chemistry_portal/directory/71/  there is a View option. When invoked it REPLACES the current window  rather than opening a new one.

The rest of the site operates a "close tab" to return to previous window.  When this is done with the view window, the previous window is hence closed and one exits the portal syste.

So could view open in a new tab to preserve the other navigational metaphors?

**Comment by cc-a** [comment]
Added via 71d015618de1a3a43f054f87e84ee55d37855f9d
