### ISSUE TITLE
Link to  Data repositories in  Profile

### ISSUE THREAD

**Issue by hrzepa** [ImperialCollegeLondon/hpc_portal#44]
The profile page shows no information about any data repositories?  What has happened to it?
![profile](https://user-images.githubusercontent.com/7828928/128623578-b46097b3-ecfb-4035-bab9-ed0df821ad97.jpg)

**Comment by hrzepa** [comment]
All attempts at publication now fail instantly?

**Comment by cc-a** [comment]
Apologies Henry. If you [restart the server](https://openondemand.rcs.ic.ac.uk/nginx/stop?redir=/pun/sys/dashboard/) and try it again it should be working now.
