### ISSUE TITLE
Add link to https://selfservice.rcs.ic.ac.uk/jobs/qstat

### ISSUE THREAD

**Issue by hrzepa** [ImperialCollegeLondon/hpc_portal#47]
In top menu, after System status, could a link to 

https://selfservice.rcs.ic.ac.uk/jobs/qstat

This allows any job reaching its time limit to be extended if that is what the user wishes to do. 

As a cosmetic change, could any job within 18 hours of its time limit  perhaps be rendered in red to alert the user?

**Comment by cc-a** [comment]
This seems somewhat equivalent to reintroducing the Active Jobs view that we agreed to remove. Changing the colour would be a bit fiddly as it involves pulling more information from the scheduler than we do at the moment.

**Comment by hrzepa** [comment]
> On 10 Aug 2021, at 10:33, Christopher Cave-Ayland ***@***.***> wrote:
> 
> 
> This seems somewhat equivalent to reintroducing the Active Jobs view that we agreed to remove.

Not really.  Can one extend job times in active view?   I want a mechanism where the user can act upon the job time information, either deleting the job, or extending its time if it is near to its nominated maximum run time.  Otherwise, it is yet another separate link that the user has to navigate to.

> Changing the colour would be a bit fiddly as it involves pulling more information from the scheduler than we do at the moment.
Fair enough.

**Comment by cc-a** [comment]
Added link via 9c4b33dac8c08cb7b2710d7cd93c38a0bcd44be9
