### ISSUE TITLE
Scaling the job list navigation

### ISSUE THREAD

**Issue by hrzepa** [ImperialCollegeLondon/hpc_portal#48]
Currently access to a job list which extends beyond one page is via the standard extra pages metaphor (below, which shows  three pages).
![Screenshot 804](https://user-images.githubusercontent.com/7828928/128735169-675fbe19-2f52-4d1a-9bc3-68a6c594dbcb.jpg)

With the old portal, this eventually grew to about 200 additional pages, whereupon this simple metaphor becomes unwieldy!  

The old portal has a somewhat ugly but functional metaphor (below) which gives almost immediate access to the approximate region of these pages.
![Screenshot 805](https://user-images.githubusercontent.com/7828928/128735835-a7a2502e-92d6-4bb1-946a-462023742c72.jpg)

So need to think if there are any other metaphors that would allow scaling up to 200 pages or beyond (PS Matt zeroed out the counter in 2016, the actual list is much larger going back to 2006!).

**Comment by cc-a** [comment]
How about this this? ![image](https://user-images.githubusercontent.com/16690296/128838255-86151518-9b7a-4fcc-813b-b2487828924b.png)

**Comment by hrzepa** [comment]
Yes, elegant!  Thanks!!


PS We are having internal meetings in chemistry to discuss the  EPSRC call for software engineering funding proposals.  I am trying to put together a 1-page "vision" for such a proposal and will float it past you for a reality check! 

Henry

**Comment by cc-a** [comment]
Added by 6c1eca2f4d2e6e2abde49a46f5dfba2f8856e207
