### ISSUE TITLE
Custom Resource values not passed through to job input

### ISSUE THREAD

**Issue by hrzepa** [ImperialCollegeLondon/hpc_portal#49]
Using the custom resource specification

**#PBS -lselect=1:ncpus=256:mem=900gb
#PBS -lwalltime=72:0:0**

the created Gaussian input file at https://openondemand.rcs.ic.ac.uk/pun/sys/chemistry_portal/directory/116/ has the headers

**%NProcShared=
%Mem=0MB
%chk=methane.chk**

where the first two original values present in the  uploaded .gjf file of  e.g.

**%nprocshared=128
%mem=20GB
 %chk=methane.chk**

have been replaced by null values which induces an error.

PS The only allowed value for ncpus in Express queues is **256** (128 is invalid)  whereas the  Gaussian code only allows up to  **128** (256  is invalid).  Matt assured me however that the job would only be charged for **128** cpus and not **256**.  Can you in fact query whether this is correct?

**Comment by hrzepa** [comment]
Get 

	• Invalid line: 'export NCORES=256 '

**Comment by cc-a** [comment]
Ah, [restart](https://openondemand.rcs.ic.ac.uk/nginx/stop?redir=/pun/sys/dashboard/) and try it again.

**Comment by hrzepa** [comment]
Get

Job submission failed /opt/ood/ondemand/root/usr/share/gems/2.7/ondemand/2.0.13/gems/ood_core-0.17.2/lib/ood_core/job/adapters/pbspro.rb:418:in `rescue in delete': qdel: illegally formed job identifier: (OodCore::JobAdapterError) from /opt/ood/ondemand/root/usr/share/gems/2.7/ondemand/2.0.13/gems/ood_core-0.17.2/lib/ood_core/job/adapters/pbspro.rb:414:in `delete' from /var/www/ood/apps/sys/chemistry_portal/main/ruby_scripts/delete.rb:8:in `

' /opt/ood/ondemand/root/usr/share/gems/2.7/ondemand/2.0.13/gems/ood_core-0.17.2/lib/ood_core/job/adapters/pbspro.rb:188:in `call': qdel: illegally formed job identifier: (OodCore::Job::Adapters::PBSPro::Batch::Error) from /opt/ood/ondemand/root/usr/share/gems/2.7/ondemand/2.0.13/gems/ood_core-0.17.2/lib/ood_core/job/adapters/pbspro.rb:163:in `delete_job' from /opt/ood/ondemand/root/usr/share/gems/2.7/ondemand/2.0.13/gems/ood_core-0.17.2/lib/ood_core/job/adapters/pbspro.rb:415:in `delete' from /var/www/ood/apps/sys/chemistry_portal/main/ruby_scripts/delete.rb:8:in `

But the job does enter the queue, although it then claims its running but produces no outputs?

**Comment by hrzepa** [comment]
For

https://openondemand.rcs.ic.ac.uk/pun/sys/chemistry_portal/directory/121/

**Comment by cc-a** [comment]
Looks like the underlying error was:
Job submission failed qsub: Job resource selection does not match any permitted configuration. Please review the job sizing guidance on: https://www.imperial.ac.uk/admin-services/ict/self-service/research-support/rcs/computing/

I've tweaked things so you should get the more informative error after a [restart](https://openondemand.rcs.ic.ac.uk/nginx/stop?redir=/pun/sys/dashboard/).

As far as I can see the job doesn't actually make it to the queue.

**Comment by hrzepa** [comment]
Chris,

Ah,  the  Custom job script and the Custom resource are not  cross-checked. 

Thus if one requests the latter which exceeds normal limits  without also specifying the former, the job will fail.

BOTH have to be specified for success, but there are no warnings if an inappropriate combination of the two is used.  A hole a user can easily fall into.
Is there any code that could trap this condition that could be inserted?

The issue now  is that one has to request 256 cpus from the resource (because 128 is not allowed) but only  128 in Gaussian (because 256 is not allowed).  I have put in a normal help desk query to sort that one out!

I am now getting the following

https://openondemand.rcs.ic.ac.uk/pun/sys/chemistry_portal/directory/128/

The gjf file submitted initially contains

%nprocshared=128
%mem=20GB
%chk=methane.chk
# wB97XD/STO-3G opt nmr freq output=wfn

Test for methane

0 1
 C                 -3.71007372    1.65847663    0.00000000
 H                 -3.35341930    0.64966663    0.00000000
 H                 -3.35340088    2.16287482    0.87365150
 H                 -3.35340088    2.16287482   -0.87365150
 H                 -4.78007372    1.65848982    0.00000000

a.wfn

but when it runs it has been re-written to 

%NProcShared=256
%Mem=0MB
%chk=methane.chk
# wB97XD/STO-3G opt nmr freq output=wfn

Test for methane

0 1
 C                 -3.71007372    1.65847663    0.00000000
 H                 -3.35341930    0.64966663    0.00000000
 H                 -3.35340088    2.16287482    0.87365150
 H                 -3.35340088    2.16287482   -0.87365150
 H                 -4.78007372    1.65848982    0.00000000

a.wfn

which fails because Gaussian cannot cope with  256 and also the memory is reset to 0MB. 

So its the re-writting of the input file that is the issue here.

SUCCESS (of a sort) at https://openondemand.rcs.ic.ac.uk/pun/sys/chemistry_portal/directory/129/

Specifying the following 

#PBS -N portal_job_00000129
#PBS -q express
#PBS -P exp-00049
#PBS -lselect=1:ncpus=256:mem=900gb
#PBS -lwalltime=72:0:0
export NCORES=128
export MEMORY_GB=200gb
produces the following input file

%NProcShared=128
%Mem=0MB
%chk=methane.chk
# wB97XD/STO-3G opt nmr freq output=wfn

Test for methane

0 1
 C                 -3.71007372    1.65847663    0.00000000
 H                 -3.35341930    0.64966663    0.00000000
 H                 -3.35340088    2.16287482    0.87365150
 H                 -3.35340088    2.16287482   -0.87365150
 H                 -4.78007372    1.65848982    0.00000000

a.wfn

So the CPUs is correct, but the memory is  NOT. 

Can you check the code that rewrites the memory in the  GJF file?

Henry

**Comment by cc-a** [comment]
Ah sorry that's my bad. The line in the resource config should just be:
```
export MEMORY_GB=900
```
without the gb at the end. That should sort the memory.
