### ISSUE TITLE
Imperial HPC  metadata record dowloads without file suggix

### ISSUE THREAD

**Issue by hrzepa** [ImperialCollegeLondon/hpc_portal#59]
Thus https://data.datacite.org/application/vnd.datacite.datacite+xml/10.14469/hpc/9031  downloads a file 

9031  without any file suffix.  It could more usefully be 9031.xml?  Could this be tweaked?

**Comment by cc-a** [comment]
That's a datacite link. We can't control the suffix datacite puts on its downloads.

**Comment by hrzepa** [comment]
I guess its the pure filename submitted by the repository.  Thus zenodo have zenodo.5511966  (which is also not optimal).

So if 9031.xml were to be submitted to  DataCite, it would download a filename with that suffix? It is annoying to have to add the suffix after download using the local computer  OS.

**Comment by cc-a** [comment]
Possibly but that would be a change to the repository. Frankly, I'm not willing to get into it.
